### ISSUE TITLE
[test] Context independent test suites

### ISSUE THREAD

**Issue by t2ym** [t2ym/live-localizer#49]
Context independent test suites have to be implemented as the current test suites are dependent on  their previous tests.

**Comment by t2ym** [comment]
`test-runner-experiments` branch for experiments.

### Issues on the branch:
1. Is the construction of test scenarios by tree-subclassing effective?
2. Can test parameters be extracted and abstracted?
3. How should test redundancies be treated?
4. Should the test html be reloaded on each test scenario as `live-localizer` cannot be re-attached to DOM due to the Firebase client initialization that can be done only once?
5. How should test scenarios with common operations at their latter steps be treated?  Should multiple inheritance of test scenarios be simulated?

**Comment by t2ym** [comment]
## Tentative Plan

### Design Principles: 
- Contexts must be explicitly handled in a concise and intuitive way in JavaScript classes
- `suite()` and `test()` in mocha are wrapped for contexts

### Alternative viewpoints for test scenarios with long and branching operations:

- Test target systems are a collection of state machines
- Operations for test suites are a series of the branches of states
- Test assertions are targeted "checkpoints" for the expected states

### Depicted test scenarios:

```
Initial -(setup op)-> First checkpoint -(op)-> 2nd CP -> ... -> Final CP for scenario A
                                               +--> ... -> Final CP for scenario B 
                                                ...
```

- Initial state is without instances of the target system
- Operations from the initial state set up test fixtures
- The first checkpoint on the first operation asserts the target instances
- Setting up the fixtures may take more steps (operations)
- Successive checkpoints constitute a series of pairs of a (mock) operation and its corresponding test assertion(s)
- Different test suites can share parts of operations and then branch in the latter parts

### Conceptual mappings for JavaScript classes:

- Operation: a (mock) operation
- Checkpoint: a collection of test assertions for a checkpoint
- Scenario: a series of Operation and Checkpoint pairs (by a prototype chain of classes?)
- Suite: a collection of Scenarios?
- Driver: driver of test suites
- Parameters: test parameters handed to constructors of test classes

### Comparison with BDD framework

- "Branching" of test contexts: Shared steps and test assertions for scenarios

**Comment by t2ym** [comment]
### Design Issues:
- [x] Namespaces/Scopes of test classes
- [x] Enumerate test classes of a namespace/scope
- [x] Trim redundant test classes
- [x] Implement driver for reconnectable tests
- [x] Partial reuse of test scenarios
- [x] `Suite.repeat` scenario operator
- [x] `Suite.permute` scenario operator
- [x] Optional Array syntax
- [x] `skipAfterFailure` static property
- [x] Optional `description` property in classes or `'TestName; Description of TestName'`
- [ ] Integrate Driver for `web-component-tester`
- [x] Integrate Runner for `web-component-tester`
- [ ] Generalize Driver/Runner for mocha, or pluggable Driver/Runner I/F
- [x] Handle constructor parameters
- [x] Babel ES5 compatibility (handle `"new Function('return class ...')"` and `=>` properly)
- [x] Modularization (Suite/Global Tests/Scopes; UMD from ES6) - `scenarist` module is created
- [ ] more...

### Tasks:
- [ ] API refinement/refactoring
- [ ] Code refinement
- [x] NodeJS support
- [ ] Documentation
- [ ] more...

**Comment by t2ym** [comment]
Close the issue since scenarist class conversion has completed for the current dialog and fab test suites.
